# Generated by Django 4.2.7 on 2024-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_color_color_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, default='product.jpg', null=True, upload_to='products'),
        ),
    ]
